const StudentData = [
  { id: 1, name: "John", marks: 85, attendance: 90, Result: "Pass" },
  { id: 2, name: "Alice", marks: 78, attendance: 92, Result: "Fail" },
  { id: 3, name: "Bob", marks: 92, attendance: 85, Result: "Pass" },
  { id: 4, name: "Emily", marks: 65, attendance: 80, Result: "Fail" },
  { id: 5, name: "Michael", marks: 70, attendance: 88, Result: "Fail" },
  { id: 6, name: "Sarah", marks: 88, attendance: 95, Result: "Pass" },
  { id: 7, name: "David", marks: 72, attendance: 91, Result: "Fail" },
  { id: 8, name: "Sophia", marks: 90, attendance: 89, Result: "Pass" },
  { id: 9, name: "James", marks: 82, attendance: 93, Result: "Pass" },
  { id: 10, name: "Emma", marks: 75, attendance: 86, Result: "Fail" },
  { id: 11, name: "Liam", marks: 80, attendance: 82, Result: "Fail" },
  { id: 12, name: "Olivia", marks: 85, attendance: 88, Result: "Pass" },
  { id: 13, name: "Noah", marks: 90, attendance: 91, Result: "Pass" },
  { id: 14, name: "Ava", marks: 79, attendance: 85, Result: "Fail" },
  {
    id: 15,
    name: "William",
    marks: 95,
    attendance: 94,
    Result: "Pass",
  },
  {
    id: 16,
    name: "Isabella",
    marks: 88,
    attendance: 89,
    Result: "Pass",
  },
  { id: 17, name: "James", marks: 75, attendance: 90, Result: "Fail" },
  { id: 18, name: "Sophia", marks: 82, attendance: 85, Result: "Pass" },
  { id: 19, name: "Oliver", marks: 87, attendance: 92, Result: "Pass" },
  {
    id: 20,
    name: "Charlotte",
    marks: 92,
    attendance: 88,
    Result: "Pass",
  },
  {
    id: 21,
    name: "Benjamin",
    marks: 78,
    attendance: 89,
    Result: "Fail",
  },
  { id: 22, name: "Amelia", marks: 83, attendance: 86, Result: "Pass" },
  { id: 23, name: "Ethan", marks: 90, attendance: 93, Result: "Pass" },
  { id: 24, name: "Harper", marks: 85, attendance: 87, Result: "Pass" },
  { id: 25, name: "Mason", marks: 74, attendance: 80, Result: "Fail" },
  { id: 26, name: "Evelyn", marks: 88, attendance: 94, Result: "Pass" },
  { id: 27, name: "Lucas", marks: 86, attendance: 90, Result: "Pass" },
  {
    id: 28,
    name: "Abigail",
    marks: 79,
    attendance: 85,
    Result: "Fail",
  },
  {
    id: 29,
    name: "Alexander",
    marks: 91,
    attendance: 92,
    Result: "Pass",
  },
  { id: 30, name: "Avery", marks: 80, attendance: 88, Result: "Fail" },
  { id: 31, name: "Daniel", marks: 87, attendance: 91, Result: "Pass" },
  { id: 32, name: "Ella", marks: 85, attendance: 87, Result: "Pass" },
  { id: 33, name: "Henry", marks: 78, attendance: 84, Result: "Fail" },
  {
    id: 34,
    name: "Scarlett",
    marks: 89,
    attendance: 93,
    Result: "Pass",
  },
  {
    id: 35,
    name: "Jackson",
    marks: 81,
    attendance: 87,
    Result: "Pass",
  },
  { id: 36, name: "Grace", marks: 84, attendance: 88, Result: "Pass" },
  {
    id: 37,
    name: "Sebastian",
    marks: 92,
    attendance: 95,
    Result: "Pass",
  },
  { id: 38, name: "Chloe", marks: 77, attendance: 83, Result: "Fail" },
  { id: 39, name: "Carter", marks: 84, attendance: 90, Result: "Pass" },
  { id: 40, name: "Riley", marks: 79, attendance: 88, Result: "Fail" },
  { id: 41, name: "Samuel", marks: 86, attendance: 91, Result: "Pass" },
  {
    id: 42,
    name: "Elizabeth",
    marks: 83,
    attendance: 86,
    Result: "Pass",
  },
  { id: 43, name: "Luna", marks: 85, attendance: 89, Result: "Pass" },
  { id: 44, name: "Joseph", marks: 90, attendance: 92, Result: "Pass" },
  {
    id: 45,
    name: "Penelope",
    marks: 88,
    attendance: 85,
    Result: "Pass",
  },
  { id: 46, name: "David", marks: 81, attendance: 88, Result: "Pass" },
  { id: 47, name: "Layla", marks: 76, attendance: 84, Result: "Fail" },
  { id: 48, name: "Wyatt", marks: 93, attendance: 91, Result: "Pass" },
  { id: 49, name: "Zoe", marks: 87, attendance: 89, Result: "Pass" },
  {
    id: 50,
    name: "Gabriel",
    marks: 80,
    attendance: 92,
    Result: "Fail",
  },
];
export default StudentData;

